#ifndef KKTEST_EXTENSIONS_FEEDBACK_INCLUDE_KKTEST_EXT_FEEDBACK_IMPL_PIPE_MESSAGE_TYPE_HPP_
#define KKTEST_EXTENSIONS_FEEDBACK_INCLUDE_KKTEST_EXT_FEEDBACK_IMPL_PIPE_MESSAGE_TYPE_HPP_

namespace kktest {
namespace feedback {

enum PipeMessageType {
    TEST,
    GROUP,
    DONE,
    ERROR
};

}  // namespace feedback
}  // namespace kktest

#endif  // KKTEST_EXTENSIONS_FEEDBACK_INCLUDE_KKTEST_EXT_FEEDBACK_IMPL_PIPE_MESSAGE_TYPE_HPP_
