#include "core/src/main.hpp"

#include "extensions/feedback/src/ext.hpp"

using namespace kktest;
using namespace cppli;
using namespace std;

KKTEST_EXPORT int main(int argc, char** argv) {
    Parser parser("Test binary. Generated by The KKTest Framework.");
    parser.addHelpFlag();

    feedback::FeedbackExtension feedbackExtension;
    feedbackExtension.registerCommandLineArgs(parser);

    InternalArgs internalArgs = registerInternalFlags(parser, KKTEST_VERSION);

    parser.interpret(argc, argv);

    return kktest::main({&feedbackExtension}, internalArgs);
}
