#ifndef KKTEST_CORE_INCLUDE_KKTEST_EXTENSION_API_HPP_
#define KKTEST_CORE_INCLUDE_KKTEST_EXTENSION_API_HPP_

#include <kktest_impl/extension_api.hpp>

#endif  // KKTEST_CORE_INCLUDE_KKTEST_EXTENSION_API_HPP_
